### ISSUE TITLE
Info on SDK Releases

### ISSUE THREAD

**Issue by uvidyadharan** [FIRST-Tech-Challenge/ftcdocs#105]
Create Section that explains changes in each release of FTC SDK

**Comment by cmacfarl** [comment]
I'm not convinced this is a good idea as it duplicates what is in the readme on the repo which introduces the likelihood of mismatched data.  There should be one source of truth and it should be the repo.

**Comment by texasdiaz** [comment]
I think the main thing we should do is have a section that explains what the SDK is, components of the SDK, maybe a little bit about how the components work (as in the AS build replaces the SDK installed on the RC, etc), and the general schedule for SDK releases. I don't necessarily agree with Craig that the information in the Readme is at all adequate as the only source of any information, it's mainly a summary. We should specifically be providing example code or annotations for the features of the SDK.

**Comment by cmacfarl** [comment]
> I don't necessarily agree with Craig that the information in the Readme is at all adequate as the only source of any information,

That's not what I said, nor is it my position.

I took @uvidyadharan's description as describing the duplication of the release notes that are present in the README on ftcdocs.  I do not think that duplicating the release notes is a good idea.  If you want a reference to the release notes on ftc docs then you can link to the header for each release in the README on FtcRobotController.  But please do not duplicate them in a raw fashion.

If you want to have sections of ftc-docs that expands on a new feature and does an in depth breakdown, that's fine.  If you want to have a section that describes the SDK architecture, sure have fun.  But please do not duplicate the release notes that are found on the public repo.  Those release notes need to be in one place and need to be the source of truth.  If you duplicate them they _will_ end up not matching at some point in time and that is not good.

**Comment by cmacfarl** [comment]
@AlecHub The only errors in the release notes section are the two references to files that are marked up with markdown link syntax wherein the author meant them to be path references as text and not urls.   The paths to the files from the root of the workspace are correct.  As to the README a fair bit of care goes into making sure the release notes are accurate and correct for each release, aside from the markup syntax that shouldn't be in the sample references, the notes are correct and complete.  But you are right, that won't be fixed until v8.1, as will the silly reference to FREIGHT FRENZY.

**Comment by AlecHub** [comment]
Editing of the Code area of the repo is not allowed so perhaps the release notes can be moved from README.md to the ./releases area of the repo, to allow the notes to be edited.  Editing of the ./wiki area of the repo is allowed so editing of the ./releases area can also be allowed.  The README.md (in the Code area) would mention that the releases are at `[Releases](./releases)`, and that the release notes accompany the releases in ./releases.

**Comment by texasdiaz** [comment]
Issue resolved in #117
