### ISSUE TITLE
Android Studio doc - Change "Disable Instant Run" to "Apply Changes" options

### ISSUE THREAD

**Issue by emcclurg** [FIRST-Tech-Challenge/ftcdocs#109]
It is useful for our team who wants to switch to Android from Blocks. Can you please confirm the following note in the documentation as I do not see the menu to Disable Instant Run in Android Studio Chipmunk version ? https://ftc-docs.firstinspires.org/programming_resources/tutorial_specific/android_studio/disable_instant_run/disable-instant-run.html . I read online that since Android Studio 4.0 it has been replaced by Apply Changes options in Run commands

**Comment by uvidyadharan** [comment]
Resolved in #118
