### ISSUE TITLE
Add PTC CAD curriculum to CAD Resources tab

### ISSUE THREAD

**Issue by emcclurg** [FIRST-Tech-Challenge/ftcdocs#122]
PTC has developed some curriculum for OnShape that is accessible to teams https://learn.onshape.com/learn/learning-path/onshape-fundamentals-cad

Do we want to have a separate tutorials tab for software providers?

**Comment by texasdiaz** [comment]
Unless the CAD curriculum is generic (not Creo or OnShape specific) I think I would prefer the tutorial to be tied to the CAD platform (the existing OnShape or Creo pages). All of the different CAD platforms have different tutorials for using their tools, though most are on other platforms (usually learning pages within their CAD domain websites). If we want a landing page that points to a wide range of tutorials, that's fine, but that's just an indexing page and doesn't contain the tutorial.

**Comment by emcclurg** [comment]
Per our discussion 10/14, add link for OnShape curriculum which allows students to use the FTC parts library via approval by PTC. Curriculum is not behind a pay wall.  Adding to the "PTC/OnShape".

**Comment by texasdiaz** [comment]
OnShape Fundamentals Training was added as part of the original document in August of 2022. Closing this.
