### ISSUE TITLE
Tech Tip page

### ISSUE THREAD

**Issue by emcclurg** [FIRST-Tech-Challenge/ftcdocs#172]
In an attempt to enlighten teams to important info living in the tech team's heads, a repo of tech tips needs to be add to ftc-doc.  This page might best serve teams if divided by categories of software (SDK, ml-toolchain, Driver Hub-specific, etc.)  This will be the reference page for the a "Tech Tip" section of the weekly team email blast that will link to this page

**Comment by emcclurg** [comment]
@uvidyadharan I'd like to see this page as a one pager with multiple topics that allows for complete visibility to the user:

SDK

Control Hub 

Driver Hub

Programming

Odometry

CAD Tips

Is there a specific way you'd like to lay these out?  Should we include Object detection?

**Comment by emcclurg** [comment]
Here's the link https://drive.google.com/drive/folders/1ig8fBWZ3Zyu2YB-23uyK0wZ0hdsAF75W

**Comment by texasdiaz** [comment]
Resolved #232
