### ISSUE TITLE
Consider adding a Control System Diagram

### ISSUE THREAD

**Issue by texasdiaz** [FIRST-Tech-Challenge/ftcdocs#2]
FRC has a really nice Control System electrical Diagram in their documentation showing all of the options for connecting an FRC control system. FTC should consider doing the same. 

For reference, here is the image:
[![image](https://user-images.githubusercontent.com/5846611/173716323-703d4330-7d84-4af6-ae11-e20e85bc6f54.png)](https://docs.wpilib.org/en/stable/_images/frc-control-system-layout-rev.svg)

**Comment by texasdiaz** [comment]
Looks like the Diagram is courtesy of FRC® Team 3161 and Stefen Acepcion. Perhaps we should reach out to them/him to do one for FTC as well.

**Comment by texasdiaz** [comment]
I've begun the process of contacting the team, I've reached out to the team's head coach Richard Balech. Stefen Acepcion is a college mentor (per their website) and maybe he or the team can help us out - at least provide us with insight on how to create it ourselves if they cannot do it for us.

**Comment by uvidyadharan** [comment]
Solved in #73
