### ISSUE TITLE
Please document that Detecting two Apriltags with same id yields "undefined behavior"

### ISSUE THREAD

**Issue by aliyoob** [FIRST-Tech-Challenge/ftcdocs#218]
Hi 
I want to detect two Apriltag with same id 
But there is a problem, the program can't distinguish the two tags. The numbers constantly keep changing and replacing each other. For example Yaw or distance are constantly keep changing between 6 to 14

**Comment by Windwoes** [comment]
Hi there -

Tracking multiple tags with the same ID is not something that is currently supported in the SDK. What I would expect to happen with the current implementation is that the `ArrayList<TagDetection>` returned to you would contain TWO objects that both report the ID number in question, but absolutely no guarantee as to the order in the list or anything like that.

What you could perhaps do is make some kind of "tracking" algorithm based on the screen coordinates from the prior frame, to track which tag is which from frame to frame.

Hope this helps!

**Comment by texasdiaz** [comment]
@aliyoob thank you for your question. This issue doesn't appear to be a *documentation* issue, which is what this ftcdocs github repository is designed to serve, but instead it appears to be a *functionality* issue. @Windwoes is correct, your specific use-case is undefined in the current system architecture. which might be a fun tiny game hint. If you have additional questions about the functionality of the AprilTag API, please post them to the [FtcRobotController Discussions area](https://github.com/FIRST-Tech-Challenge/FtcRobotController/discussions). If there are issues that we need to address in documenting the AprilTag or VisionPortal APIs, we can create issues here in this repository.

Good luck this season!

**Comment by texasdiaz** [comment]
Sorry, we'll keep this issue open for the documentation issue, but if you have additional *functionality* questions please be sure to ask away in the [FtcRobotController Discussions area](https://github.com/FIRST-Tech-Challenge/FtcRobotController/discussions) or on the [FTC-Community technical forums](https://ftc-community.firstinspires.org/).

**Comment by emcclurg** [comment]
This would be a good Tech Tip though.
