### ISSUE TITLE
False information about controller stick calibration in latest Tech Tip

### ISSUE THREAD

**Issue by qwertychouskie** [FIRST-Tech-Challenge/ftcdocs#256]
![image](https://github.com/FIRST-Tech-Challenge/ftcdocs/assets/13989090/c1d77c71-fc05-4242-a4ed-92f61f36a097)

The highlighted text is patently false.  To calibrate the stick center points on a DualShock 4 controller, you need to use https://github.com/carpikes/ds4-tools, and there is currently no known way to do thins on a DualSense (PS5) controller (hopefully someone finds a way to dump and reverse-engineer the firmware to get the needed HID commands to perform the calibration function).

**Comment by qwertychouskie** [comment]
Those are just saying to reset in case it's some sort of connection issue, which is more applicable to wireless use anyways.  It doesn't actually re-calibrate the center point stored in the firmware.

**Comment by rachmo** [comment]
@texasdiaz  can this be closed?

**Comment by texasdiaz** [comment]
Yes, I'll close this. The tech tip posted to ftc-docs has been corrected.

**Comment by qwertychouskie** [comment]
It should probably be noted that now the DualSense can also be calibrated, and the process is also easier now: https://dualshock-tools.github.io/

Might be worth adding to the doc.
