### ISSUE TITLE
FAQ Page for rookies (Needed for Kickoff)

### ISSUE THREAD

**Issue by texasdiaz** [FIRST-Tech-Challenge/ftcdocs#49]
Need an FAQ page for rookies.

**Comment by emcclurg** [comment]
@uvidyadharan  Sending you an unformatted Word doc for this. Do you think it can be ready by 9/13?
[Team FAQs.docx](https://github.com/FIRST-Tech-Challenge/ftcdocs/files/9528258/Team.FAQs.docx)

Also adding the doc to the Drive folder

**Comment by uvidyadharan** [comment]
Will do
