### ISSUE TITLE
Add "About FTC Kahoot" link to TOC

### ISSUE THREAD

**Issue by emcclurg** [FIRST-Tech-Challenge/ftcdocs#96]
[https://create.kahoot.it/course/f79560a1-df68-44dd-bbef-d8c9bf5a27f5](url)

This is a fun self-led FIRST Tech Challenge Kahoot to test and build your knowledge. Learn about the many facets of FIRST Tech Challenge and the Core Values of FIRST.

**Comment by texasdiaz** [comment]
This sounds like it can be a section hanging off the About FIRST Tech Challenge page.
